title: "Evolución del Crimen en Latinoamérica 2015-2024: Base de Dat"
description: "Base de datos sobre la evoluci&oacute;n del crimen en Am&eacute;rica Latina y el Caribe durante el per&iacute;odo 2015-2024, compilada a partir de fue"
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/evolucion-del-crimen-en-latinoamerica-2015-2024-base-de-datos-por-categorias"
